on:
  push:
  workflow_dispatch:


jobs:

  build_libretro:
    strategy:
      matrix:
        arch: [so64, x86, x64]
        core: [64, 64sc, 64dtv, 128, scpu64, plus4, cbm2, cbm5x0, pet, vic]
      fail-fast: false


    runs-on: ubuntu-latest


    steps:

    - uses: li1ht2ay-3es/vi1e-l2br3tr4@build
      with:
        branch: custom

        arch: ${{ matrix.arch }}
        core: ${{ matrix.core }}

        token: ${{ secrets.token }}
